CREATE TABLE IF NOT EXISTS products(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    stock INT DEFAULT 1 UNSIGNED,
    price INT DEFAULT 1 UNSIGNED,
    image TEXT
)